//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.209
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.0.3705.209.
// 
namespace art_emotherearth_ws.localhost {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="OrderStatusSoapBinding", Namespace="http://localhost:8080/emotherearth/services/OrderStatus")]
    public class OrderInfoService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public OrderInfoService() {
            string urlSetting = System.Configuration.ConfigurationSettings.AppSettings["art_emotherearth_ws.localhost:8080.OrderInfoService"];
            if ((urlSetting != null)) {
                this.Url = string.Concat(urlSetting, "");
            }
            else {
                this.Url = "http://localhost:8080/emotherearth/services/OrderStatus";
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://localhost:8080/emotherearth/services/OrderStatus", ResponseNamespace="http://localhost:8080/emotherearth/services/OrderStatus")]
        [return: System.Xml.Serialization.SoapElementAttribute("getWsDescriptionReturn")]
        public string getWsDescription() {
            object[] results = this.Invoke("getWsDescription", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetWsDescription(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getWsDescription", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetWsDescription(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://localhost:8080:8080/emotherearth/services/OrderStatus", ResponseNamespace="http://localhost:8080:8080/emotherearth/services/OrderStatus")]
        [return: System.Xml.Serialization.SoapElementAttribute("getOrderStatusReturn")]
        public string getOrderStatus(int orderKey) {
            object[] results = this.Invoke("getOrderStatus", new object[] {
                        orderKey});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetOrderStatus(int orderKey, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getOrderStatus", new object[] {
                        orderKey}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetOrderStatus(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://localhost:8080/emotherearth/services/OrderStatus", ResponseNamespace="http://localhost:8080/emotherearth/services/OrderStatus")]
        [return: System.Xml.Serialization.SoapElementAttribute("getShippingStatusReturn")]
        public string getShippingStatus(int orderKey) {
            object[] results = this.Invoke("getShippingStatus", new object[] {
                        orderKey});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetShippingStatus(int orderKey, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getShippingStatus", new object[] {
                        orderKey}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetShippingStatus(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
}
