--
-- Clean up old versions
--

BEGIN;
use eMotherEarth;
DROP TABLE IF EXISTS KEY_TABLE;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS PRODUCTS;
DROP TABLE IF EXISTS LINEITEMS;
DROP TABLE IF EXISTS ORDERS;
DROP DATABASE IF EXISTS eMotherEarth;
COMMIT;

CREATE DATABASE eMotherEarth;
USE eMotherEarth;


--
-- Users
-- Non-transactional


CREATE TABLE USERS (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(20) NOT NULL,
  ADDRESS1 VARCHAR(50),
  ADDRESS2 VARCHAR(50),
  CITY VARCHAR(20),
  STATE VARCHAR(2),
  ZIP VARCHAR(10),
  CONSTRAINT PK_ID PRIMARY KEY (ID)
) type=MYISAM;

CREATE INDEX NAME_ORDER ON USERS(NAME);


INSERT INTO USERS (NAME, ADDRESS1, ADDRESS2, CITY, STATE, ZIP) VALUES ('Homer', '845 Georgia Spring Pk', ' ', 'Springfield', 'OH', '32322');
INSERT INTO USERS (NAME, ADDRESS1, ADDRESS2, CITY, STATE, ZIP) VALUES ('Monty', '180 Red Southeast Xchng', 'Ste 433', 'Paris', 'TX', '498543');
INSERT INTO USERS (NAME, ADDRESS1, ADDRESS2, CITY, STATE, ZIP) VALUES ('Maggie', '569 Peachtree Summer Ct',' ', 'Atlanta', 'GA', '30339');
INSERT INTO USERS (NAME, ADDRESS1, ADDRESS2, CITY, STATE, ZIP) VALUES ('Bart', '664 Winter State Xchng', '#3', 'San Francisco', 'CA', '98434');
INSERT INTO USERS (NAME, ADDRESS1, ADDRESS2, CITY, STATE, ZIP) VALUES ('Waylon', '54 E First St', '', 'Springfield', 'OH', '43984');
COMMIT;

--
-- Products
-- Non-transactional

CREATE TABLE PRODUCTS (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(100),
  PRICE DOUBLE PRECISION,
  CONSTRAINT PK_ID PRIMARY KEY (ID)
) type=MYISAM;

CREATE INDEX PRODUCTSINDEXPK ON PRODUCTS (ID)  ;


BEGIN;
INSERT INTO PRODUCTS (NAME, PRICE) values ("Ocean", 1393456200.00);
INSERT INTO PRODUCTS (NAME, PRICE) values ("Leaves (green)", 3.5);
INSERT INTO PRODUCTS (NAME, PRICE) values ("Leaves (brown)", 0.01);
INSERT INTO PRODUCTS (NAME, PRICE) values ("Mountain", 2694381.34);
INSERT INTO PRODUCTS (NAME, PRICE) values ("Lake", 34563.12);
INSERT INTO PRODUCTS (NAME, PRICE) values ("Snow", 2.45);
INSERT INTO PRODUCTS (NAME, PRICE) values ("Grass (short)", 0.12);
INSERT INTO PRODUCTS (NAME, PRICE) values ("Grass (long)", 0.18);
INSERT INTO PRODUCTS (NAME, PRICE) values ("Dirt", 0.89);
INSERT INTO PRODUCTS (NAME, PRICE) values ("Tree - Oak", 45.78);
INSERT INTO PRODUCTS (NAME, PRICE) values ("Tree - Maple", 34.90);
INSERT INTO PRODUCTS (NAME, PRICE) values ("Tree - Pine", 12.50);
INSERT INTO PRODUCTS (NAME, PRICE) values ("Seaweed", 0.45);
INSERT INTO PRODUCTS (NAME, PRICE) values ("Sand", 0.15);
INSERT INTO PRODUCTS (NAME, PRICE) values ("Clay", 0.11);
INSERT INTO PRODUCTS (NAME, PRICE) values ("Sea", 6943942.03);
INSERT INTO PRODUCTS (NAME, PRICE) values ("Volcano ", 234242.12);
INSERT INTO PRODUCTS (NAME, PRICE) values ("Island (deserted)", 4390853.33);

COMMIT;


--
-- Orders
-- transactional



CREATE TABLE ORDERS (
    ORDER_KEY INTEGER NOT NULL AUTO_INCREMENT,
    USER_KEY INTEGER NOT NULL,
    ORDER_STATUS Varchar(3),
    SHIPPING_STATUS Varchar(3),
    CC_TYPE Varchar(20),
    CC_NUM Varchar(20),
    CC_EXP Varchar(10),
    CONSTRAINT PK_ORDER PRIMARY KEY (ORDER_KEY)
) type=MYISAM;

BEGIN;
INSERT INTO ORDERS (USER_KEY, ORDER_STATUS, SHIPPING_STATUS, CC_TYPE, CC_NUM, CC_EXP) VALUES (2, "P", "P", "Visa", "4333-3333-3333-3333", "10/03");
INSERT INTO ORDERS (USER_KEY, ORDER_STATUS, SHIPPING_STATUS, CC_TYPE, CC_NUM, CC_EXP) VALUES (2, "S", "D", "MC", "5333-3333-3333-3333", "1/03");
INSERT INTO ORDERS (USER_KEY, ORDER_STATUS, SHIPPING_STATUS, CC_TYPE, CC_NUM, CC_EXP) VALUES (1, "B", "P", "Amex", "3733-444444-14000", "12/04");
INSERT INTO ORDERS (USER_KEY, ORDER_STATUS, SHIPPING_STATUS, CC_TYPE, CC_NUM, CC_EXP) VALUES (3, "S", "D","Amex", "3333-333333-33333", "01/05");
INSERT INTO ORDERS (USER_KEY, ORDER_STATUS, SHIPPING_STATUS, CC_TYPE, CC_NUM, CC_EXP) VALUES (4, "B", "A","MC", "5555-5555-5555-5555", "10/01");
COMMIT;


--
-- Line items
-- transactional

CREATE TABLE LINEITEMS (
    LINEITEM_KEY INTEGER NOT NULL AUTO_INCREMENT,
    ORDER_KEY INTEGER NOT NULL,
    ITEM_ID INTEGER NOT NULL,
    QUANTITY INTEGER NOT NULL,
    CONSTRAINT PK_LINEITEM PRIMARY KEY (LINEITEM_KEY)
) type=MYISAM;

BEGIN;
INSERT INTO LINEITEMS (ORDER_KEY, ITEM_ID, QUANTITY) VALUES (1, 3, 3);
INSERT INTO LINEITEMS (ORDER_KEY, ITEM_ID, QUANTITY) VALUES (1, 1, 2);
INSERT INTO LINEITEMS (ORDER_KEY, ITEM_ID, QUANTITY) VALUES (1, 4, 1);
INSERT INTO LINEITEMS (ORDER_KEY, ITEM_ID, QUANTITY) VALUES (1, 6, 2);
INSERT INTO LINEITEMS (ORDER_KEY, ITEM_ID, QUANTITY) VALUES (2, 7, 1);
INSERT INTO LINEITEMS (ORDER_KEY, ITEM_ID, QUANTITY) VALUES (2, 1, 2);
INSERT INTO LINEITEMS (ORDER_KEY, ITEM_ID, QUANTITY) VALUES (2, 3, 1);
INSERT INTO LINEITEMS (ORDER_KEY, ITEM_ID, QUANTITY) VALUES (2, 5, 2);
INSERT INTO LINEITEMS (ORDER_KEY, ITEM_ID, QUANTITY) VALUES (2, 7, 4);
INSERT INTO LINEITEMS (ORDER_KEY, ITEM_ID, QUANTITY) VALUES (2, 2, 3);
INSERT INTO LINEITEMS (ORDER_KEY, ITEM_ID, QUANTITY) VALUES (2, 4, 32);
INSERT INTO LINEITEMS (ORDER_KEY, ITEM_ID, QUANTITY) VALUES (3, 6, 3);
INSERT INTO LINEITEMS (ORDER_KEY, ITEM_ID, QUANTITY) VALUES (3, 3, 2);
INSERT INTO LINEITEMS (ORDER_KEY, ITEM_ID, QUANTITY) VALUES (3, 8, 3);
INSERT INTO LINEITEMS (ORDER_KEY, ITEM_ID, QUANTITY) VALUES (4, 1, 31);
INSERT INTO LINEITEMS (ORDER_KEY, ITEM_ID, QUANTITY) VALUES (5, 1, 6);
INSERT INTO LINEITEMS (ORDER_KEY, ITEM_ID, QUANTITY) VALUES (5, 3, 3);
INSERT INTO LINEITEMS (ORDER_KEY, ITEM_ID, QUANTITY) VALUES (5, 2, 8);
INSERT INTO LINEITEMS (ORDER_KEY, ITEM_ID, QUANTITY) VALUES (5, 3, 2);
INSERT INTO LINEITEMS (ORDER_KEY, ITEM_ID, QUANTITY) VALUES (5, 4, 1);
COMMIT;


--
-- set up user for web applications
--
grant all on eMotherEarth.* to webuser@"%" identified by "webpass";
